name: Snapshot

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente a buildear'
        required: true
        type: choice
        options:
          - dev
          - uat
      version:
        description: 'Version tag (ej: 1.0.0)'
        required: true
        default: 'latest'

permissions:
  contents: read
  id-token: write

jobs:
  snapshot:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Remove gcloud credential helper
        run: |
          cat ~/.docker/config.json || true
          docker logout us-central1-docker.pkg.dev || true

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_ENV=${{ github.event.inputs.environment }} \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/autozone-qa-repo/autozone-qa-fe:${{ github.event.inputs.version }} \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/autozone-qa-repo/autozone-qa-fe:latest \
            .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/autozone-qa-repo/autozone-qa-fe:${{ github.event.inputs.version }}
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/autozone-qa-repo/autozone-qa-fe:latest
